# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 23:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_encuesta', models.CharField(max_length=255)),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('visitas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EncuestaRespuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=255)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=255)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaElegida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Pregunta')),
                ('respuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Respuesta')),
                ('respuesta_encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.EncuestaRespuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.CharField(max_length=255)),
                ('contrasenia', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='encuesta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor.Usuario'),
        ),
    ]
